import {inter, poppins} from "@/fonts/fonts";
import "./globals.css";
import Providers from "@/lib/Providers";
import Header from "@/components/shared/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <main>{children}</main>
          <footer></footer>
        </Providers>
      </body>
    </html>
  );
}
